CREATE TABLE `TABLES` (
	`TABLE_CATALOG` VARCHAR(512) NOT NULL DEFAULT '',
	`TABLE_SCHEMA` VARCHAR(64) NOT NULL DEFAULT '',
	`TABLE_NAME` VARCHAR(64) NOT NULL DEFAULT '',
	`TABLE_TYPE` VARCHAR(64) NOT NULL DEFAULT '',
	`ENGINE` VARCHAR(64) NULL DEFAULT NULL,
	`VERSION` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`ROW_FORMAT` VARCHAR(10) NULL DEFAULT NULL,
	`TABLE_ROWS` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`AVG_ROW_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`MAX_DATA_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`INDEX_LENGTH` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`DATA_FREE` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`AUTO_INCREMENT` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`CREATE_TIME` DATETIME NULL DEFAULT NULL,
	`UPDATE_TIME` DATETIME NULL DEFAULT NULL,
	`CHECK_TIME` DATETIME NULL DEFAULT NULL,
	`TABLE_COLLATION` VARCHAR(32) NULL DEFAULT NULL,
	`CHECKSUM` BIGINT(21) UNSIGNED NULL DEFAULT NULL,
	`CREATE_OPTIONS` VARCHAR(255) NULL DEFAULT NULL,
	`TABLE_COMMENT` VARCHAR(2048) NOT NULL DEFAULT ''
)
COLLATE='utf8_general_ci'
ENGINE=MEMORY
;
